### ISSUE TITLE
Missing Metrics

### ISSUE THREAD

**Issue by lanceofwhichwedream** [tobbez/deluge_exporter#4]
I'm using your exporter script currently and I'm finding that it's no longer outputting a good number of the metrics that it used to. Does this script need a bit of an update?

Deluge version: 2.0.3-2-201906121747-ubuntu18.04.1
Deluge is running in docker, however I checked the code in the python interpreter and looks like the endpoints/metrics have changed.

**Comment by tobbez** [comment]
I'm not aware of any recent changes that would require an update.

A number of libtorrent metrics (`deluge_libtorrent_*`) were previously removed when the exporter was updated for Deluge 2. The metrics are still exposed, but they have new names.

If you are missing other metrics, you need to provide more details:

* Which version of deluge_exporter?
* Which metrics are missing?
* Since when did the metrics go missing?

**Comment by lanceofwhichwedream** [comment]
@tobbez I apologize, this bug report is in error.
